### PR TITLE
Add Dependent Destory To Versioned Content

### PR DESCRIPTION
**Pull request by michaelwehrley**
Add Dependent Destroy To Versioned Content

* Add `dependent: destroy` to class `VersionedContent`
* All associated `click_events` will be destroyed

[Finishes: #95022744]

### CODE REVIEW

**Comment by ericcf** [comment]
Do you really want to throw away click events?

**Comment by michaelwehrley** [comment]
You make an excellent point; however, if we don't know the version of content, wouldn't that make the click event datum meaningless?

**Comment by ericcf** [comment]
Possibly, but I'd argue that a conservative approach might be prudent here: prevent destroying Versioned Content if there are associated click events. What do you think about using the `dependent: :restrict_with_error` option instead?

**Comment by michaelwehrley** [comment]
An excellent solution. Thank you and thank you rails!

**Comment by michaelwehrley** [comment]
Thanks for the help!

**Pull request merged**
